# Generated by Django 4.2.1 on 2023-06-08 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=50, unique=True)),
                ('account_balance', models.DecimalField(decimal_places=4, max_digits=12)),
                ('account_type', models.CharField(max_length=50)),
                ('account_status', models.CharField(default='active', max_length=50)),
                ('opening_date', models.DateTimeField(null=True)),
                ('last_transaction_date', models.DateTimeField(null=True)),
            ],
        ),
    ]
