# Generated by Django 4.2.2 on 2023-07-13 11:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=200, unique=True)),
                ('account_balance', models.DecimalField(decimal_places=4, max_digits=12)),
                ('account_type', models.CharField(max_length=50)),
                ('account_status', models.CharField(default='active', max_length=50)),
                ('opening_date', models.DateTimeField(null=True)),
                ('last_transaction_date', models.DateTimeField(null=True)),
                ('first_name', models.CharField(default='Savingsf', max_length=100)),
                ('last_name', models.CharField(default='Savingsl', max_length=100)),
                ('total_withdraw', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('total_deposit', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('total_transfar', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('total_paybil', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('total_trans_amount', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Agents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('id_number', models.CharField(max_length=50, unique=True)),
                ('dealer_id', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_number', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=False)),
                ('agent_number', models.CharField(blank=True, max_length=50, null=True)),
                ('registered_on', models.DateField(auto_now_add=True)),
                ('image', models.ImageField(default='default.jpg', upload_to='agents_pics')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('approved', models.BooleanField(default=False)),
                ('admin_review', models.BooleanField(default=False)),
                ('registered_on', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dealers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('id_number', models.CharField(max_length=50, unique=True)),
                ('dealer_id', models.CharField(max_length=50, unique=True)),
                ('contact_number', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('registered_on', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(default='default.jpg', upload_to='dealer_pics')),
            ],
        ),
        migrations.CreateModel(
            name='Saving_account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(default='saving', max_length=50)),
                ('account_number', models.CharField(max_length=1000, unique=True)),
                ('deposit', models.DecimalField(decimal_places=4, max_digits=12)),
                ('account_balance', models.DecimalField(decimal_places=4, max_digits=12)),
                ('last_transaction_date', models.DateTimeField(null=True)),
                ('account_type', models.CharField(max_length=100)),
                ('transaction_count', models.CharField(default=0, max_length=100)),
                ('opening_date', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TillNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='till_numbers', to='savings.agents')),
            ],
        ),
        migrations.CreateModel(
            name='Target_saving_record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saving_for', models.CharField(max_length=100)),
                ('target_amount', models.CharField(max_length=100)),
                ('amount_saved', models.CharField(default=0, max_length=100)),
                ('balence_amount', models.CharField(default=0, max_length=100)),
                ('progress', models.CharField(default=0, max_length=100)),
                ('saving_par_time', models.CharField(max_length=100)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Statements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=12)),
                ('transaction_date', models.DateTimeField()),
                ('account_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='savings.account')),
            ],
        ),
        migrations.CreateModel(
            name='Saving_record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=100)),
                ('date_saved', models.DateTimeField()),
                ('account_number', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Saving_account_statements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=12)),
                ('transaction_date', models.DateTimeField()),
                ('account_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='savings.saving_account')),
            ],
        ),
        migrations.CreateModel(
            name='BusinessNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buss_number', models.CharField(max_length=50)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_numbers', to='savings.company')),
            ],
        ),
    ]
