# Generated by Django 4.2.1 on 2023-06-13 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0006_rename_amount_saving_record_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='target_saving_record',
            name='amount_saved',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
