# Generated by Django 4.2.1 on 2023-06-13 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0007_target_saving_record_amount_saved'),
    ]

    operations = [
        migrations.AddField(
            model_name='target_saving_record',
            name='balence_amount',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
