# Generated by Django 4.2.2 on 2023-06-15 10:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0010_statements'),
    ]

    operations = [
        migrations.AddField(
            model_name='statements',
            name='amount',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statements',
            name='transaction_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statements',
            name='transaction_type',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='statements',
            name='account_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='savings.account'),
        ),
    ]
