# Generated by Django 4.2.2 on 2023-06-20 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0012_saving_account_saving_account_statements'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saving_account',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='saving_account',
            name='last_name',
        ),
        migrations.AddField(
            model_name='saving_account',
            name='account_name',
            field=models.CharField(default='saving', max_length=50),
        ),
    ]
