# Generated by Django 4.2.2 on 2023-06-20 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0013_remove_saving_account_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saving_account',
            name='last_transaction_date',
            field=models.DateTimeField(null=True),
        ),
    ]
