# Generated by Django 4.2.2 on 2023-06-20 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0014_saving_account_last_transaction_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='total_deposit',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='account',
            name='total_trans_amount',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='account',
            name='total_transfar',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='account',
            name='total_withdraw',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
    ]
