# Generated by Django 4.2.2 on 2023-07-05 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0015_account_total_deposit_account_total_trans_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saving_account',
            name='account_number',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
