# Generated by Django 4.2.2 on 2023-07-05 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0016_alter_saving_account_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
