# Generated by Django 4.2.2 on 2023-07-05 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0018_alter_saving_account_account_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='total_paybil',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
    ]
