# Generated by Django 4.2.2 on 2023-07-12 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0021_dealers_rename_registed_on_agents_registered_on_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TillNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='till_numbers', to='savings.agents')),
            ],
        ),
    ]
