# Generated by Django 4.2.2 on 2023-07-06 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0021_rename_registed_on_agents_registered_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dealers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('id_number', models.CharField(max_length=50, unique=True)),
                ('dealer_id', models.CharField(max_length=50, unique=True)),
                ('contact_number', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('registered_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='agents',
            name='dealer_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
