# Generated by Django 4.2.2 on 2023-07-12 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0022_tillnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='agents',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='agents_pics'),
        ),
        migrations.AddField(
            model_name='dealers',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='dealer_pics'),
        ),
    ]
