# Generated by Django 4.2.2 on 2023-07-12 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0024_company_businessnumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='contry',
            new_name='country',
        ),
    ]
