# Generated by Django 4.2.2 on 2023-07-12 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0025_rename_contry_company_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
