# Generated by Django 4.2.2 on 2023-07-12 16:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0028_rename_number_businessnumber_buss_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='registered_on',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='businessnumber',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_numbers', to='savings.company'),
        ),
    ]
